Financial Stocks Web Application
d2ndjim/financial-stocks pull request #2
Opened 2022-06-22 13:48 UTC by d2ndjim

- Installed working dev dependencies
- Fetched and displayed data from API using redux toolkit react-redux
- Route company stocks to company profiles
- Add responsiveness to web application.
- Live Presentation @ `https://www.loom.com/share/776cf75201ee4f25893f4b41122b83a2`

2022-06-22 15:01 UTC, medaminedev66 requested changes
Hi @d2ndjim  😃, :wave:, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
- Your app works as expected and runs without errors.
- Your code organization was perfect.

## Required Changes ♻️
- [ ] Following the project requirements, The video should contain a highlight about a piece of the code you find interesting or are proud of making. Try to open Visual Studio Code or whatever IDE you are using while you are recording a video and try to present a piece of code that interests you.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-22 15:01 UTC, medaminedev66 commented on src/__tests__/app.test.js
> +});
- [ ] Following the project requirements, your app should have unit tests for several components, and also should have integration tests using React Testing Library. Check out this [link ](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/articles/testing_react_with_react_testing_library.md) to learn about React Testing Library.

2022-06-23 13:36 UTC, julie-ify approved these changes
Hi @d2ndjim,

✔️ Good presentation
✔️ Good design

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

# Status: Approved ✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-23 13:40 UTC, closed without merging

2022-06-23 13:43 UTC, d2ndjim commented
Thank you.

On Thu, 23 Jun 2022, 14:36 Juliana Ifionu, ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> Hi @d2ndjim <https://github.com/d2ndjim>,
>
> ✔️ Good presentation
> ✔️ Good design
>
> Your project is complete! There is nothing else to say other than... it's
> time to merge it [image: :shipit:]
> Congratulations! 🎉
> Status: Approved ✔️
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/d2ndjim/financial-stocks/pull/2#pullrequestreview-1017022706>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARQJIRD6KJPS67I72DIZ66TVQRR47ANCNFSM5ZQJOIIA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>